import { Tabs } from "antd";
import { Metadata } from "next";
import Dot from "~/components/common/dot";
import CardProject from "~/components/ui/card-project";
import { CategoryType, projects } from "~/utils/projects";

export const metadata: Metadata = {
  title: "Portfolio - Projects",
  description: "Generated by create next app",
};

type CategoryItem = {
  id: CategoryType | "all";
  name: string;
};

const allCategory = projects
  .map((p) => [...p.categories])
  .reduce((acc, item) => {
    return [...acc, ...item];
  }, []);
const setCategories = new Set(allCategory);
const arrayCategory = Array.from(setCategories).map(
  (c): CategoryItem => ({
    id: c,
    name: c,
  })
);

const categories: CategoryItem[] = [
  {
    id: "all",
    name: "All",
  },
  ...arrayCategory,
];

const filterProject = (category: CategoryType) => {
  return projects.filter((p) => p.categories.includes(category)) || [];
};

export default function ProjectsPage() {
  return (
    <section className="min-h-screen pt-12 dark:bg-bgDark2">
      <div className="container mx-auto px-[10px] lg:px-0">
        <div className="w-full flex gap-x-[10px] justify-center items-center mb-8 lg:mb-16 mx-auto">
          <div className="w-[20px] h-[20px] text-main">
            <Dot />
          </div>
          <h2 className="h2">
            <span>My Projects</span>
          </h2>
        </div>
        {/* Tabs */}
        <Tabs
          defaultActiveKey="all"
          items={categories.map((category: CategoryItem) => {
            return {
              key: category.id,
              label: <span className="capitalize">{category.name}</span>,
              children: (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-[16px]">
                  {(category.id === "all"
                    ? projects
                    : filterProject(category.id)
                  ).map((item) => (
                    <CardProject key={item.id} data={item} />
                  ))}
                </div>
              ),
            };
          })}
        />
      </div>
    </section>
  );
}
