import { Metadata } from "next";
import AboutMe from "~/components/common/home/about-me";
import Cta from "~/components/common/home/cta";
import General from "~/components/common/home/general";
import Projects from "~/components/common/home/projects";

export const metadata: Metadata = {
  title: "Portfolio - WinDev",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <General />
      <AboutMe />
      <Projects />
      <Cta />
    </>
  );
}
